export const texts = {
    ES: {
        TITLE_INDEX: "IberCS - Inicio",
        TITLE_REGISTER: "IberCS - Crear cuenta",
        TITLE_LOGIN: "IberCS - Entrar en la cuenta",
        TITLE_PROFILE: "IberCS - Mi perfil",
        TITLE_FORUM: "IberCS - Foro",
        TITLE_LADDER: "IberCS - Ranking",
        TITLE_MATCHES: "IberCS - Partidos",
        REGISTER_Button: "Registrarse",
        LOGIN_Button: "Entrar",
        PROFILE_Invitations: "Invitaciones",
        NAVBAR_USERMENU_Profile: "Mi perfil",
        NAVBAR_Inicio: "Inicio",
        NAVBAR_Forum: "Foro",
        NAVBAR_Ladder: "Ranking",
        NAVBAR_Matches: "Partidos",
        NAVBAR_Entrar: "Entrar",
        NAVBAR_Language: "Lenguaje",
        FORUM_Title: "Últimos hilos",
        FORUM_Search: "Buscar",
        FORUM_NewThread: "Nuevo hilo",
        FORUM_NewThread_Title: "Título",
        FORUM_NewThread_Submit: "Crear hilo",
        FORUM_NewPost_Submit: "Añadir respuesta",
        FORUM_NumberOfPosts: "Respuestas",
        ADDONS_Title: "Streamers online",
        FACEIT_Connect: "Conectar con Faceit",
        FACEIT_Connected: "Conectado con Faceit",
        LADDER_BUTTON_players: "Jugadores",
        LADDER_BUTTON_teams: "Equipos",
        LADDER_FieldUsername: "Usuario",
        LADDER_FieldNickname: "Faceit Nickname",
        LADDER_FieldElo: "Elo",
        LADDER_HelpPlayer: "Para aparecer en la tabla, debes tener cuenta de Faceit y conectarla en tu perfil.",
        MATCHES_Upcoming: "Próximos partidos",
        MATCHES_Ongoing: "Partidos en curso",
        MATCHES_Ended: "Partidos terminados",
        RETURN: "Volver",
        EXIT: "Salir",
        SAVE: "Guardar",
    },
    PT: {
        TITLE_INDEX: "IberCS - Início",
        TITLE_REGISTER: "IberCS - Criar conta",
        TITLE_LOGIN: "IberCS - Entrar na conta",
        TITLE_PROFILE: "IberCS - Meu perfil",
        TITLE_FORUM: "IberCS - Fórum",
        TITLE_LADDER: "IberCS - Classificação",
        TITLE_MATCHES: "IberCS - Partidas",
        REGISTER_Button: "Registar",
        LOGIN_Button: "Entrar",
        PROFILE_Invitations: "Convites",
        NAVBAR_USERMENU_Profile: "Meu perfil",
        NAVBAR_Inicio: "Inicio",
        NAVBAR_Forum: "Fórum",
        NAVBAR_Ladder: "Classificação",
        NAVBAR_Matches: "Partidas",
        NAVBAR_Entrar: "ENTRAR",
        FORUM_Title: "Últimos tópicos",
        FORUM_Search: "Pesquisar",
        FORUM_NewThread: "Novo tópico",
        FORUM_NewPost_Submit: "Adicionar resposta",
        FORUM_NewThread_Title: "Título",
        FORUM_NewThread_Submit: "Criar tópico",
        FORUM_NumberOfPosts: "Respostas",
        ADDONS_Title: "Streamers online",
        FACEIT_Connect: "Ligar com Faceit",
        FACEIT_Connected: "Ligado com Faceit",
        LADDER_BUTTON_players: "Jogadores",
        LADDER_BUTTON_teams: "Equipas",
        LADDER_FieldUsername: "Utilizador",
        LADDER_FieldNickname: "Faceit Nickname",
        LADDER_FieldElo: "Elo",
        LADDER_HelpPlayer: "Para aparecer na tabela, deves ter conta de Faceit e ligá-la no teu perfil.",
        MATCHES_Upcoming: "Próximas partidas",
        MATCHES_Ongoing: "Partidas em curso",
        MATCHES_Ended: "Partidas terminadas",
        RETURN: "Voltar",
        EXIT: "Sair",
        SAVE: "Guardar",
    },
};
