// I want to find text["PT"].NAVBAR_Inicio

export const texts = {
    ES: {
        REGISTER_Button: "Registrarse",
        LOGIN_Button: "Entrar",
        NAVBAR_USERMENU_Profile: "Mi perfil",
        NAVBAR_Inicio: "Inicio",
        NAVBAR_Forum: "Foro",
        NAVBAR_Ladder: "Ranking",
        NAVBAR_Entrar: "Entrar",
        NAVBAR_Language: "Lenguaje",
        FORUM_Title: "Últimos hilos",
        FORUM_Search: "Buscar",
        FORUM_NewThread: "Nuevo hilo",
        FORUM_NewThread_Title: "Título",
        FORUM_NewThread_Submit: "Crear hilo",
        FORUM_NewPost_Submit: "Añadir respuesta",
        FORUM_NumberOfPosts: "Respuestas",
        ADDONS_Title: "Streamers online",
        FACEIT_Connect: "Conectar con Faceit",
        FACEIT_Connected: "Conectado con Faceit",
        LADDER_BUTTON_players: "Jugadores",
        LADDER_BUTTON_teams: "Equipos",
        LADDER_FieldUsername: "Usuario",
        LADDER_FieldNickname: "Faceit Nickname",
        LADDER_FieldElo: "Elo",
        RETURN: "Volver",
        EXIT: "Salir",
    },
    PT: {
        REGISTER_Button: "Registar",
        LOGIN_Button: "Entrar",
        NAVBAR_USERMENU_Profile: "Meu perfil",
        NAVBAR_Inicio: "Inicio",
        NAVBAR_Forum: "Fórum",
        NAVBAR_Ladder: "Classificação",
        NAVBAR_Entrar: "ENTRAR",
        FORUM_Title: "Últimos tópicos",
        FORUM_Search: "Pesquisar",
        FORUM_NewThread: "Novo tópico",
        FORUM_NewPost_Submit: "Adicionar resposta",
        FORUM_NewThread_Title: "Título",
        FORUM_NewThread_Submit: "Criar tópico",
        FORUM_NumberOfPosts: "Respostas",
        ADDONS_Title: "Streamers online",
        FACEIT_Connect: "Ligar com Faceit",
        FACEIT_Connected: "Ligado com Faceit",
        LADDER_BUTTON_players: "Jogadores",
        LADDER_BUTTON_teams: "Equipas",
        LADDER_FieldUsername: "Utilizador",
        LADDER_FieldNickname: "Faceit Nickname",
        LADDER_FieldElo: "Elo",
        RETURN: "Voltar",
        EXIT: "Sair",
    },
};
