// I want to find text["PT"].NAVBAR_Inicio

export const texts = {
    ES: {
        REGISTER_Button: "Registrarse",
        LOGIN_Button: "Entrar",
        NAVBAR_USERMENU_Profile: "Mi perfil",
        NAVBAR_Inicio: "Inicio",
        NAVBAR_Forum: "Foro",
        NAVBAR_Ladder: "Ranking",
        NAVBAR_Entrar: "Entrar",
        NAVBAR_Language: "Lenguaje",
        FORUM_Title: "Últimos hilos",
        FORUM_Search: "Buscar",
        FORUM_NumberOfPosts: "Respuestas",
        ADDONS_Title: "Streamers online",
        LADDER_BUTTON_players: "Jugadores",
        LADDER_BUTTON_teams: "Equipos",
        RETURN: "Volver",
        EXIT: "Salir",
    },
    PT: {
        REGISTER_Button: "Registar",
        LOGIN_Button: "Entrar",
        NAVBAR_USERMENU_Profile: "Meu perfil",
        NAVBAR_Inicio: "Inicio",
        NAVBAR_Forum: "Fórum",
        NAVBAR_Ladder: "Classificação",
        NAVBAR_Entrar: "ENTRAR",
        FORUM_Title: "Últimos tópicos",
        FORUM_Search: "Pesquisar",
        FORUM_NumberOfPosts: "Respostas",
        ADDONS_Title: "Streamers online",
        LADDER_BUTTON_players: "Jogadores",
        LADDER_BUTTON_teams: "Equipas",
        RETURN: "Voltar",
        EXIT: "Sair",
    },
};
